 name: tutorial_climate_ai
    channels:
      - conda-forge
    dependencies:
      - python=3.9
      - pip
      - numpy
      - pandas
      - matplotlib
      - pytorch
      - torchvision
      - xarray 
      - pip:
        - -r requirements.txt # (Optional: If you have a requirements.txt file)
